# name of the sequence data. Also used as folder name.
output_name: "2021-02-20"

# fasta file to be analyzed
fasta_file: "sub20k.fa"
msa: "msa_25k.fasta"
fasta_folder: "resources/genomes/2021-02-09"

# number of sequence in the subset
subset: 5000

# info file of the new sequences
info_file: "metadata_2021-02-09_18-08.tsv"
info_folder: "resources/genomes/2021-02-09"

# filter samples by time interval 
time_window: "2019-01-01:2022-01-01"

# True: do not add to existing alignment, make a new one from scratch.
# False: add to the last produced alignment. 
from_scratch: true

# repeat the tree construction
redo: true

# reference fasta file
reference_fa: "sars_cov_2_reference_genome.fa"

# reference genbank file (used for rule translate)
reference_gb: "sars_cov_2_reference_genome_MN985325.gb"

# cdhit parameters
cdhit: [0.99]



