# name of the sequence data. Also used as folder name.
output_name: "2021-02-09"

# fasta file to be analyzed
fasta_file: "sequences_2021-02-09_08-13.fasta"
msa: "msa_0210.fasta"
fasta_folder: "resources/genomes/2021-02-09"

# number of sequence in the subset
subset: 30000

# info file of the new sequences
info_file: "metadata_2021-02-09_18-08.tsv"
info_folder: "resources/genomes/2021-02-09"

# filter samples by time interval 
time_window: "2019-01-01:2022-01-01"

# repeat the tree construction
redo: true

# reference fasta file
reference_fa: "sars_cov_2_reference_genome.fa"

# reference gff file
reference_gff: "sars_cov_2_reference_genome.gff"

# cdhit parameters
cdhit: [0.99, 0.995, 0.999, 0.9999]



